name: Test Email Send

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test-email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Send test email
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
      run: python test_send.py
    
    - name: Send test success notification
      if: success()
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
      run: |
        python -c "
        import smtplib
        from email.mime.text import MIMEText
        from datetime import datetime
        import os
        
        smtp_server = 'smtp.gmail.com'
        smtp_port = 587
        sender_email = os.getenv('SENDER_EMAIL')
        sender_password = os.getenv('SENDER_PASSWORD')
        recipient = 'salongadaviid@gmail.com'
        
        subject = '✅ Test Email Workflow Completed Successfully'
        body = 'Success! Test emails have been sent successfully. Recipients: Azor Lanac and David Salonga. Sent from GitHub Actions (Test Workflow) ' + datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')
        
        msg = MIMEText(body)
        msg['Subject'] = subject
        msg['From'] = f'David Salonga <{sender_email}>'
        msg['To'] = recipient
        
        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            server.send_message(msg)
        print('Test success notification sent!')
        "